### ISSUE TITLE
Configuration Export has some parsing errors

### ISSUE THREAD

**Issue by surfer190** [hbagdi/deck#14] opened 2019-04-24 09:14 UTC
After doing a `deck dump` and then running a `kong config parse kong.yaml` it has showns a few discrepencies:

1. No `'_format_version':` - needed at the top of the file
2. A null value was added for an empty field:

```
  plugins:
  - name: request-transformer
    config:
      add:
        body: []
        headers: []
        querystring:
        - fmt:json
        - period:d
      append:
        body: []
        headers: []
        querystring: []
      http_method: null
```

**Comment by hbagdi** [comment] 2019-04-24 17:27
@surfer190 decK is nearly compatible with Kong's native declarative configuration but not completely yet.
Please add `_format_version: "1.1"` as a top level YAML property and it should work.

**Comment by hbagdi** [comment] 2019-05-02 03:35
Closing this as it is not a bug or feature request. Please re-open if otherwise. Thanks!

**Closed by hbagdi** 2019-05-02 03:35 UTC

**Comment by surfer190** [comment] 2019-12-03 09:22
`http_method: null` should not exists as per https://github.com/Kong/kong-plugin-request-transformer/issues/10#event-2845996946
