### ISSUE TITLE
deck sync fails after dump: Error: checking workspace 'my-project' in Kong: Not found

### ISSUE THREAD

**Issue by ecostanzi** [hbagdi/deck#155] opened 2020-05-22 07:59 UTC
I'm trying to sync a declarative configuration with kong (version 1.3-enterprise-edition, trial version on aws). `deck dump` works, but `deck sync` fails even without touching the synced file.

```
$ deck dump --headers "kong-admin-token:XXXXX" --kong-addr "https://admin-intesyssrlc9de7c.kong-cloud.com/" --workspace my-project
$ cat kong.yaml
_format_version: "1.1"
_workspace: my-project
$ deck sync --headers "kong-admin-token:XXXXXXX" --kong-addr "https://admin-intesyssrlc9de7c.kong-cloud.com/"
Error: checking workspace 'my-project' in Kong: Not found
```

I'm running deck on an ubuntu linux subsystem.
```
$ deck version
decK v1.1.0 (acdb161)
```

<details>
  <summary>Verbose dump</summary>
  
```
GET // HTTP/1.1
Host: admin-intesyssrlc9de7c.kong-cloud.com
User-Agent: Go-http-client/1.1
Accept-Encoding: gzip


HTTP/1.1 200 OK
Content-Length: 12262
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: https://manager-intesyssrlc9de7c.kong-cloud.com
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Date: Fri, 22 May 2020 07:56:55 GMT
Kong-Cloud-Request-Id: 4a9bf798eaa967a89d4d683290cfe282
Kong-Cloud-Request-Id: 33bd1d7d90fd94a84db29f9c1fdd5fad
Server: openresty/1.15.8.2
Strict-Transport-Security: max-age=31536000
Vary: Origin
X-Kong-Admin-Request-Id: pOSNQjZXfUUSAdPj2IdIXQo1nFZvmUbx

{"plugins":{"enabled_in_cluster":["rate-limiting-advanced"],"available_on_server":{"graphql-rate-limiting-advanced":true,"vault-auth":true,"correlation-id":true,"request-transformer-advanced":true,"cors":true,"ldap-auth":true,"route-transformer-advanced":true,"hmac-auth":true,"oauth2-introspection":true,"rate-limiting-advanced":true,"bot-detection":true,"azure-functions":true,"ldap-auth-advanced":true,"openid-connect":true,"response-transformer":true,"ip-restriction":true,"jwt":true,"proxy-cache":true,"graphql-proxy-cache-advanced":true,"key-auth":true,"kafka-upstream":true,"upstream-tls":true,"session":true,"forward-proxy":true,"basic-auth":true,"response-transformer-advanced":true,"jwt-signer":true,"oauth2":true,"request-validator":true,"mtls-auth":true,"acl":true,"route-by-header":true,"degraphql":true,"proxy-cache-advanced":true,"exit-transformer":true,"response-ratelimiting":true,"aws-lambda":true,"canary":true,"request-transformer":true,"request-termination":true}},"tagline":"Welcome to kong","configuration":{"plugins":["acl","aws-lambda","azure-functions","basic-auth","bot-detection","canary","correlation-id","cors","degraphql","exit-transformer","forward-proxy","graphql-proxy-cache-advanced","graphql-rate-limiting-advanced","hmac-auth","ip-restriction","jwt","jwt-signer","kafka-upstream","key-auth","ldap-auth","ldap-auth-advanced","mtls-auth","oauth2","oauth2-introspection","openid-connect","proxy-cache","proxy-cache-advanced","rate-limiting-advanced","request-termination","request-transformer","request-transformer-advanced","request-validator","response-ratelimiting","response-transformer","response-transformer-advanced","route-by-header","route-transformer-advanced","session","upstream-tls","vault-auth"],"portal_auth_login_attempts":0,"portal_reset_success_email":true,"admin_listen":["0.0.0.0:5351"],"proxy_access_log":"logs\/access.log","prefix":"\/usr\/local\/kong\/intesyssrlc9de7c","portal_gui_host":"portal-intesyssrlc9de7c.kong-cloud.com","vitals_statsd_udp_packet_size":1024,"cassandra_username":"kong","rbac_auth_header":"Kong-Admin-Token","audit_log_ignore_tables":{},"vitals_prometheus_scrape_interval":5,"admin_gui_ssl_cert_default":"\/usr\/local\/kong\/intesyssrlc9de7c\/ssl\/admin-gui-kong-default.crt","vitals_tsdb_address":"vitalsprom.active.kong-aws-us-east-1:9042","smtp_timeout_read":60000,"nginx_http_upstream_directives":[{"value":"60s","name":"keepalive_timeout"},{"value":"60","name":"keepalive"},{"value":"100","name":"keepalive_requests"}],"nginx_user":"intesyssrlc9de7c kong-shared","pg_semaphore_timeout":60000,"smtp_username":"8dbee42b-d284-487b-9f72-575302fd4d25","client_ssl_cert_default":"\/usr\/local\/kong\/intesyssrlc9de7c\/ssl\/kong-default.crt","portal_invite_email":true,"dns_no_sync":false,"db_update_propagation":0,"stream_listen":["off"],"vitals_strategy":"prometheus","cassandra_port":9042,"headers":["server_tokens","latency_tokens","X-Kong-Upstream-Status"],"portal_gui_ssl_cert_key_default":"\/usr\/local\/kong\/intesyssrlc9de7c\/ssl\/portal-gui-kong-default.key","cassandra_lb_policy":"RequestRoundRobin","origins":{},"portal_emails_from":"noreply@kongcloud.io","admin_approved_email":"true","pg_database":"intesyssrlc9de7c","admin_gui_ssl_enabled":false,"admin_gui_auth_login_attempts":0,"lua_package_cpath":"","portal_cors_origins":{},"admin_acc_logs":"\/usr\/local\/kong\/intesyssrlc9de7c\/logs\/admin_access.log","cassandra_refresh_frequency":60,"nginx_pid":"\/usr\/local\/kong\/intesyssrlc9de7c\/pids\/nginx.pid","admin_gui_listen":["0.0.0.0:5352"],"cassandra_contact_points":["127.0.0.1"],"admin_gui_auth_header":"******","proxy_listeners":[{"listener":"0.0.0.0:5350","proxy_protocol":false,"reuseport":false,"transparent":false,"ssl":false,"ip":"0.0.0.0","deferred":false,"http2":false,"port":5350,"bind":false}],"tracing_write_strategy":"file","db_cache_warmup_entities":["services","plugins"],"enabled_headers":{"latency_tokens":true,"X-Kong-Proxy-Latency":true,"Via":true,"server_tokens":true,"Server":true,"X-Kong-Upstream-Latency":true,"X-Kong-Upstream-Status":true},"nginx_http_ssl_protocols":"TLSv1.1 TLSv1.2 TLSv1.3","admin_emails_from":"noreply@kongcloud.io","smtp_auth_type":"plain","admin_gui_listeners":[{"listener":"0.0.0.0:5352","proxy_protocol":false,"reuseport":false,"transparent":false,"ssl":false,"ip":"0.0.0.0","deferred":false,"http2":false,"port":5352,"bind":false}],"pg_ssl":false,"admin_gui_access_log":"logs\/admin_gui_access.log","proxy_url":"https:\/\/intesyssrlc9de7c.kong-cloud.com:443","smtp_timeout_send":60000,"kong_env":"\/usr\/local\/kong\/intesyssrlc9de7c\/.kong_env","portal_gui_listeners":[{"listener":"0.0.0.0:5353","proxy_protocol":false,"reuseport":false,"transparent":false,"ssl":false,"ip":"0.0.0.0","deferred":false,"http2":false,"port":5353,"bind":false}],"log_level":"notice","portal_api_ssl_cert_key_default":"\/usr\/local\/kong\/intesyssrlc9de7c\/ssl\/portal-api-kong-default.key","admin_ssl_cert_key_default":"\/usr\/local\/kong\/intesyssrlc9de7c\/ssl\/admin-kong-default.key","vitals_ttl_seconds":3600,"real_ip_recursive":"off","cassandra_repl_factor":1,"portal_api_error_log":"logs\/error.log","router_consistency":"strict","pg_port":6432,"admin_gui_url":"https:\/\/manager-intesyssrlc9de7c.kong-cloud.com","ssl_preread_enabled":true,"cassandra_keyspace":"kong","ssl_cert_default":"\/usr\/local\/kong\/intesyssrlc9de7c\/ssl\/kong-default.crt","route_validation_strategy":"smart","portal_approved_email":true,"error_default_type":"text\/plain","tracing_types":{"1":"all","all":true},"tracing":false,"admin_ssl_enabled":false,"admin_emails_reply_to":"noreply@kongcloud.io","trusted_ips":["127.0.0.1"],"client_max_body_size":"0","nginx_http_upstream_keepalive_requests":"100","portal_is_legacy":false,"vitals_statsd_prefix":"kong.intesyssrlc9de7c","audit_log_record_ttl":2592000,"portal_auth":"basic-auth","audit_log":true,"pg_host":"pgbouncer-trials03.service.kong-aws-us-east-1","pg_user":"intesyssrlc9de7c","mem_cache_size":"64m","audit_log_ignore_methods":{},"nginx_admin_directives":{},"cassandra_ssl":false,"admin_gui_auth":"basic-auth","smtp_domain":"localhost.localdomain","portal_api_url":"https:\/\/portal-intesyssrlc9de7c.kong-cloud.com\/_api","nginx_http_directives":[{"value":"TLSv1.1 TLSv1.2 TLSv1.3","name":"ssl_protocols"},{"value":"http-conf.d\/*","name":"include"}],"smtp_port":587,"smtp_host":"smtp.postmarkapp.com","vitals_statsd_address":"127.0.0.1:8125","nginx_daemon":"on","vitals_ttl_minutes":90000,"portal_access_request_email":true,"portal_gui_protocol":"https","ssl_cert_csr_default":"\/usr\/local\/kong\/intesyssrlc9de7c\/ssl\/kong-default.csr","smtp_mock":false,"db_update_frequency":5,"audit_log_ignore_paths":{},"lua_ssl_verify_depth":1,"dns_stale_ttl":4,"nginx_kong_stream_conf":"\/usr\/local\/kong\/intesyssrlc9de7c\/nginx-kong-stream.conf","dns_resolver":{},"admin_ssl_cert_default":"\/usr\/local\/kong\/intesyssrlc9de7c\/ssl\/admin-kong-default.crt","dns_order":["A","CNAME","LAST","SRV"],"dns_error_ttl":1,"proxy_error_log":"logs\/error.log","tracing_time_threshold":0,"cassandra_data_centers":["dc1:2","dc2:3"],"feature_conf_path":"\/etc\/kong\/intesyssrlc9de7c\/feature.conf","admin_gui_flags":"{ \"HIDE_DASHBOARD\" : true , \"MOCK_SERVICE_MAP\" : false, \"MOCK_ALERTS\": false }","nginx_sproxy_directives":{},"nginx_http_upstream_keepalive_timeout":"60s","smtp_password":"******","pg_timeout":5000,"portal_email_verification":false,"smtp_timeout_connect":60000,"database":"postgres","admin_gui_ssl_cert_key_default":"\/usr\/local\/kong\/intesyssrlc9de7c\/ssl\/admin-gui-kong-default.key","admin_gui_session_conf":"******","smtp_ssl":false,"admin_invitation_expiry":259200,"nginx_worker_processes":"1","admin_api_uri":"https:\/\/manager-intesyssrlc9de7c.kong-cloud.com\/_api","ssl_ciphers":"ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256","portal_auto_approve":false,"nginx_proxy_access_log":"logs\/access-json.log ls_json","smtp_admin_emails":["noreply@kongcloud.io"],"nginx_http_include":"http-conf.d\/*","lua_package_path":".\/?.lua;.\/?\/init.lua;","client_ssl":false,"upstream_keepalive":60,"vitals_delete_interval_pg":30,"portal_api_ssl_cert_default":"\/usr\/local\/kong\/intesyssrlc9de7c\/ssl\/portal-api-kong-default.crt","admin_gui_error_log":"logs\/admin_gui_error.log","portal_gui_use_subdomains":false,"pg_max_concurrent_queries":0,"smtp_starttls":true,"proxy_listen":["0.0.0.0:5350"],"vitals_flush_interval":10,"proxy_ssl_enabled":false,"nginx_http_upstream_keepalive":"60","portal_api_listeners":[{"listener":"0.0.0.0:5354","proxy_protocol":false,"reuseport":false,"transparent":false,"ssl":false,"ip":"0.0.0.0","deferred":false,"http2":false,"port":5354,"bind":false}],"lua_socket_pool_size":30,"ssl_cipher_suite":"modern","portal_api_listen":["0.0.0.0:5354"],"db_resurrect_ttl":30,"portal":true,"cassandra_consistency":"ONE","portal_token_exp":21600,"admin_error_log":"logs\/error.log","pg_ssl_verify":false,"dns_not_found_ttl":30,"db_cache_ttl":0,"pg_password":"******","portal_session_conf":"******","cassandra_repl_strategy":"SimpleStrategy","enforce_rbac":"on","admin_access_log":"logs\/admin_access.log","portal_api_access_log":"logs\/portal_api_access.log","generate_trace_details":false,"nginx_kong_conf":"\/usr\/local\/kong\/intesyssrlc9de7c\/nginx-kong.conf","real_ip_header":"X-Real-IP","dns_hostsfile":"\/etc\/hosts","admin_listeners":[{"listener":"0.0.0.0:5351","proxy_protocol":false,"reuseport":false,"transparent":false,"ssl":false,"ip":"0.0.0.0","deferred":false,"http2":false,"port":5351,"bind":false}],"nginx_acc_logs":"\/usr\/local\/kong\/intesyssrlc9de7c\/logs\/access.log","portal_reset_email":true,"nginx_portal_api_acc_logs":"\/usr\/local\/kong\/intesyssrlc9de7c\/logs\/portal_api_access.log","client_ssl_cert_key_default":"\/usr\/local\/kong\/intesyssrlc9de7c\/ssl\/kong-default.key","cassandra_ssl_verify":false,"cassandra_timeout":5000,"portal_gui_listen":["0.0.0.0:5353"],"cassandra_schema_consensus_timeout":10000,"portal_gui_ssl_cert_default":"\/usr\/local\/kong\/intesyssrlc9de7c\/ssl\/portal-gui-kong-default.crt","nginx_proxy_directives":[{"value":"logs\/access-json.log ls_json","name":"access_log"}],"portal_gui_ssl_enabled":false,"anonymous_reports":false,"nginx_conf":"\/usr\/local\/kong\/intesyssrlc9de7c\/nginx.conf","nginx_stream_directives":{},"nginx_err_logs":"\/usr\/local\/kong\/intesyssrlc9de7c\/logs\/error.log","ssl_cert_key_default":"\/usr\/local\/kong\/intesyssrlc9de7c\/ssl\/kong-default.key","client_body_buffer_size":"1m","rbac":"on","portal_api_ssl_enabled":false,"vitals":true,"nginx_optimizations":true,"loaded_plugins":{"graphql-rate-limiting-advanced":true,"vault-auth":true,"session":true,"request-transformer-advanced":true,"cors":true,"ldap-auth":true,"route-transformer-advanced":true,"hmac-auth":true,"oauth2-introspection":true,"rate-limiting-advanced":true,"bot-detection":true,"azure-functions":true,"ldap-auth-advanced":true,"oauth2":true,"response-transformer":true,"ip-restriction":true,"jwt":true,"proxy-cache":true,"basic-auth":true,"key-auth":true,"kafka-upstream":true,"graphql-proxy-cache-advanced":true,"request-transformer":true,"forward-proxy":true,"upstream-tls":true,"correlation-id":true,"response-ratelimiting":true,"exit-transformer":true,"request-validator":true,"mtls-auth":true,"acl":true,"route-by-header":true,"proxy-cache-advanced":true,"degraphql":true,"openid-connect":true,"response-transformer-advanced":true,"aws-lambda":true,"canary":true,"jwt-signer":true,"request-termination":true},"stream_listeners":{},"portal_emails_reply_to":"noreply@kongcloud.io"},"version":"1.3-enterprise-edition","license":{"customer":"cloud","license_creation_date":"2018-05-31","product_subscription":"Kong Enterprise Edition","admin_seats":"100","support_plan":"Standard","license_expiration_date":"2028-03-16"},"node_id":"ed881f54-d23e-4fe9-9770-8e2979b32f74","lua_version":"LuaJIT 2.1.0-beta3","prng_seeds":{"pid: 16318":591821951571,"pid: 16336":138213251385},"timers":{"pending":10,"running":0},"hostname":"kongshared-trials03-03965aad320c07f75.kong-aws-us-east-1"}
GET //workspaces/my-project HTTP/1.1
Host: admin-intesyssrlc9de7c.kong-cloud.com
User-Agent: Go-http-client/1.1
Accept-Encoding: gzip


HTTP/1.1 404 Not Found
Content-Length: 23
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: https://manager-intesyssrlc9de7c.kong-cloud.com
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Date: Fri, 22 May 2020 07:56:55 GMT
Kong-Cloud-Request-Id: 6d0454e243df477dff5b3ee52d44071c
Server: openresty/1.15.8.2
Strict-Transport-Security: max-age=31536000
Vary: Origin
X-Kong-Admin-Request-Id: oDVuKmqJSXa0HOVv0ilS59f8XURwisxJ

{"message":"Not found"}
Error: checking workspace 'my-project' in Kong: Not found

```
</details>

**Comment by hbagdi** [comment] 2020-05-27 23:24
You need to manually create a workspace in Kong before you can use decK against that workspace.

**Comment by ecostanzi** [comment] 2020-05-28 08:25
@hbagdi the workspace I mentioned is already created manually in kong.

When the workspace does not exists it shows an error when using dump command:
```
deck dump --headers "kong-admin-token:XXXXX" --kong-addr "https://admin-intesyssrlc9de7c.kong-cloud.com/" --workspace doesnotexists
Error: reading configuration from Kong: services: Not found
```

When the workspace exists the dump command correctly creates the kong.yml file locally, but the sync command fails.

**Comment by hbagdi** [comment] 2020-05-29 16:37
I'm not sure what could be causing that. I tried myself and couldn't reproduce.
Are you using a special `admin-token` or the root one that you received when you signed up?

**Comment by satwant17** [comment] 2020-05-29 17:52
can you please change sync kong-addr and remove the last "/"
deck sync --headers "kong-admin-token:XXXXXXX" --kong-addr "https://admin-intesyssrlc9de7c.kong-cloud.com"

**Comment by hbagdi** [comment] 2020-05-29 17:56
That's painful. Tracking the root cause in https://github.com/hbagdi/deck/issues/161.

**Comment by ecostanzi** [comment] 2020-05-30 07:15
@satwant17 it worked, thanks!

**Comment by hbagdi** [comment] 2020-06-01 15:54
Closing this since the root problem is being tracked in #161

**Closed by hbagdi** 2020-06-01 15:54 UTC
